/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Activity,
  ActivityCreate,
  ActivityKind,
  HTTPValidationError,
} from '../models/index';
import {
    ActivityFromJSON,
    ActivityToJSON,
    ActivityCreateFromJSON,
    ActivityCreateToJSON,
    ActivityKindFromJSON,
    ActivityKindToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface CreateActivityRequest {
    activityCreate: ActivityCreate;
}

export interface GetActivityRequest {
    activityId: number;
}

export interface ListActivitiesRequest {
    includeInactive?: boolean;
    textSearch?: string | null;
    moduleId?: number | null;
    kind?: ActivityKind | null;
}

export interface UpdateActivityRequest {
    activityId: number;
    activityCreate: ActivityCreate;
}

/**
 * 
 */
export class ActivitiesApi extends runtime.BaseAPI {

    /**
     * Endp Create Activity
     */
    async createActivityRaw(requestParameters: CreateActivityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Activity>> {
        if (requestParameters['activityCreate'] == null) {
            throw new runtime.RequiredError(
                'activityCreate',
                'Required parameter "activityCreate" was null or undefined when calling createActivity().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/activities`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ActivityCreateToJSON(requestParameters['activityCreate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ActivityFromJSON(jsonValue));
    }

    /**
     * Endp Create Activity
     */
    async createActivity(requestParameters: CreateActivityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Activity> {
        const response = await this.createActivityRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Endp Get Activity
     */
    async getActivityRaw(requestParameters: GetActivityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Activity>> {
        if (requestParameters['activityId'] == null) {
            throw new runtime.RequiredError(
                'activityId',
                'Required parameter "activityId" was null or undefined when calling getActivity().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/activities/{activity_id}`;
        urlPath = urlPath.replace(`{${"activity_id"}}`, encodeURIComponent(String(requestParameters['activityId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ActivityFromJSON(jsonValue));
    }

    /**
     * Endp Get Activity
     */
    async getActivity(requestParameters: GetActivityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Activity> {
        const response = await this.getActivityRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Activities
     */
    async listActivitiesRaw(requestParameters: ListActivitiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Activity>>> {
        const queryParameters: any = {};

        if (requestParameters['includeInactive'] != null) {
            queryParameters['include_inactive'] = requestParameters['includeInactive'];
        }

        if (requestParameters['textSearch'] != null) {
            queryParameters['text_search'] = requestParameters['textSearch'];
        }

        if (requestParameters['moduleId'] != null) {
            queryParameters['module_id'] = requestParameters['moduleId'];
        }

        if (requestParameters['kind'] != null) {
            queryParameters['kind'] = requestParameters['kind'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/activities`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ActivityFromJSON));
    }

    /**
     * List Activities
     */
    async listActivities(requestParameters: ListActivitiesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Activity>> {
        const response = await this.listActivitiesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Endp Update Activity
     */
    async updateActivityRaw(requestParameters: UpdateActivityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Activity>> {
        if (requestParameters['activityId'] == null) {
            throw new runtime.RequiredError(
                'activityId',
                'Required parameter "activityId" was null or undefined when calling updateActivity().'
            );
        }

        if (requestParameters['activityCreate'] == null) {
            throw new runtime.RequiredError(
                'activityCreate',
                'Required parameter "activityCreate" was null or undefined when calling updateActivity().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/activities/{activity_id}`;
        urlPath = urlPath.replace(`{${"activity_id"}}`, encodeURIComponent(String(requestParameters['activityId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ActivityCreateToJSON(requestParameters['activityCreate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ActivityFromJSON(jsonValue));
    }

    /**
     * Endp Update Activity
     */
    async updateActivity(requestParameters: UpdateActivityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Activity> {
        const response = await this.updateActivityRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
