/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GenerateCourseResponse,
  HTTPValidationError,
} from '../models/index';
import {
    GenerateCourseResponseFromJSON,
    GenerateCourseResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface GenerateCourseApiV1AgentsGenerateCoursePostRequest {
    courseId: number;
}

/**
 * 
 */
export class AgentsApi extends runtime.BaseAPI {

    /**
     * Endpoint pro generování kurzu z obsahu.
     * Generate Course
     */
    async generateCourseApiV1AgentsGenerateCoursePostRaw(requestParameters: GenerateCourseApiV1AgentsGenerateCoursePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GenerateCourseResponse>> {
        if (requestParameters['courseId'] == null) {
            throw new runtime.RequiredError(
                'courseId',
                'Required parameter "courseId" was null or undefined when calling generateCourseApiV1AgentsGenerateCoursePost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['courseId'] != null) {
            queryParameters['course_id'] = requestParameters['courseId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/agents/generate-course`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GenerateCourseResponseFromJSON(jsonValue));
    }

    /**
     * Endpoint pro generování kurzu z obsahu.
     * Generate Course
     */
    async generateCourseApiV1AgentsGenerateCoursePost(requestParameters: GenerateCourseApiV1AgentsGenerateCoursePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GenerateCourseResponse> {
        const response = await this.generateCourseApiV1AgentsGenerateCoursePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
