/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  Module,
  ModuleCreate,
  ModuleUpdate,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ModuleFromJSON,
    ModuleToJSON,
    ModuleCreateFromJSON,
    ModuleCreateToJSON,
    ModuleUpdateFromJSON,
    ModuleUpdateToJSON,
} from '../models/index';

export interface CreateModuleRequest {
    moduleCreate: ModuleCreate;
}

export interface DeleteModuleRequest {
    moduleId: number;
}

export interface GetModuleRequest {
    moduleId: number;
}

export interface ListModulesRequest {
    includeInactive?: boolean;
    textSearch?: string | null;
    courseId?: number | null;
}

export interface UpdateModuleRequest {
    moduleId: number;
    moduleUpdate: ModuleUpdate;
}

/**
 * 
 */
export class ModulesApi extends runtime.BaseAPI {

    /**
     * Endp Create Module
     */
    async createModuleRaw(requestParameters: CreateModuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Module>> {
        if (requestParameters['moduleCreate'] == null) {
            throw new runtime.RequiredError(
                'moduleCreate',
                'Required parameter "moduleCreate" was null or undefined when calling createModule().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/modules`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ModuleCreateToJSON(requestParameters['moduleCreate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModuleFromJSON(jsonValue));
    }

    /**
     * Endp Create Module
     */
    async createModule(requestParameters: CreateModuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Module> {
        const response = await this.createModuleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Endp Delete Module
     */
    async deleteModuleRaw(requestParameters: DeleteModuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['moduleId'] == null) {
            throw new runtime.RequiredError(
                'moduleId',
                'Required parameter "moduleId" was null or undefined when calling deleteModule().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/modules/{module_id}`;
        urlPath = urlPath.replace(`{${"module_id"}}`, encodeURIComponent(String(requestParameters['moduleId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Endp Delete Module
     */
    async deleteModule(requestParameters: DeleteModuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteModuleRaw(requestParameters, initOverrides);
    }

    /**
     * Endp Get Module
     */
    async getModuleRaw(requestParameters: GetModuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Module>> {
        if (requestParameters['moduleId'] == null) {
            throw new runtime.RequiredError(
                'moduleId',
                'Required parameter "moduleId" was null or undefined when calling getModule().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/modules/{module_id}`;
        urlPath = urlPath.replace(`{${"module_id"}}`, encodeURIComponent(String(requestParameters['moduleId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModuleFromJSON(jsonValue));
    }

    /**
     * Endp Get Module
     */
    async getModule(requestParameters: GetModuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Module> {
        const response = await this.getModuleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Modules
     */
    async listModulesRaw(requestParameters: ListModulesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Module>>> {
        const queryParameters: any = {};

        if (requestParameters['includeInactive'] != null) {
            queryParameters['include_inactive'] = requestParameters['includeInactive'];
        }

        if (requestParameters['textSearch'] != null) {
            queryParameters['text_search'] = requestParameters['textSearch'];
        }

        if (requestParameters['courseId'] != null) {
            queryParameters['course_id'] = requestParameters['courseId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/modules`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ModuleFromJSON));
    }

    /**
     * List Modules
     */
    async listModules(requestParameters: ListModulesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Module>> {
        const response = await this.listModulesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Endp Update Module
     */
    async updateModuleRaw(requestParameters: UpdateModuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Module>> {
        if (requestParameters['moduleId'] == null) {
            throw new runtime.RequiredError(
                'moduleId',
                'Required parameter "moduleId" was null or undefined when calling updateModule().'
            );
        }

        if (requestParameters['moduleUpdate'] == null) {
            throw new runtime.RequiredError(
                'moduleUpdate',
                'Required parameter "moduleUpdate" was null or undefined when calling updateModule().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/modules/{module_id}`;
        urlPath = urlPath.replace(`{${"module_id"}}`, encodeURIComponent(String(requestParameters['moduleId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ModuleUpdateToJSON(requestParameters['moduleUpdate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModuleFromJSON(jsonValue));
    }

    /**
     * Endp Update Module
     */
    async updateModule(requestParameters: UpdateModuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Module> {
        const response = await this.updateModuleRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
