services:
  frontend:
    build:
      context: .
      dockerfile: infra/docker/fe.Dockerfile
      args:
        NEXT_PUBLIC_KEYCLOAK_URL: ${NEXT_PUBLIC_KEYCLOAK_URL}
        NEXT_PUBLIC_KEYCLOAK_REALM: ${NEXT_PUBLIC_KEYCLOAK_REALM}
        NEXT_PUBLIC_KEYCLOAK_CLIENT_ID: ${NEXT_PUBLIC_KEYCLOAK_CLIENT_ID}
        NEXT_API_URL: ${NEXT_API_URL}
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - praktikai
    depends_on:
      - api
  api:
    build:
      context: .
      dockerfile: infra/docker/backend.Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/code
    networks:
      - praktikai
    depends_on:
      - db

  db:
    image: pgvector/pgvector:0.8.1-pg18-trixie
    restart: always
    shm_size: 128mb
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES__PASSWORD}
      POSTGRES_USER: ${POSTGRES__USER}
      POSTGRES_DB: ${POSTGRES__DB}
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - "5433:5432" 
    networks:
      - praktikai
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES__DB} -U ${POSTGRES__USER}"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.0

    depends_on:
      - db
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "false"
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/${POSTGRES__DB}?currentSchema=keycloak
      KC_DB_USERNAME: ${POSTGRES__USER}
      KC_DB_PASSWORD: ${POSTGRES__PASSWORD}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
    command: start-dev --import-realm
    ports:
      - "8080:8080"
      - "9000:9000"
    volumes:
      - ./infra/keycloak-themes/praktik-ai:/opt/keycloak/themes/praktik-ai
      - ./infra/keycloak/praktikai-dev-realm.json:/opt/keycloak/data/import/praktikai-dev-realm.json:ro
    networks:
      - praktikai


  seaweedfs-master:
    image: chrislusf/seaweedfs:latest
    command: master -mdir=/data -ip=seaweedfs-master -port=9333
    ports:
      - "9333:9333"
    volumes:
      - seaweedfs-master-data:/data
    networks:
      - praktikai
    restart: unless-stopped

  seaweedfs-volume:
    image: chrislusf/seaweedfs:latest
    command: volume -mserver=seaweedfs-master:9333 -dir=/data -port=8081 -ip=seaweedfs-volume
    ports:
      - "8081:8081"
    volumes:
      - seaweedfs-volume-data:/data
    networks:
      - praktikai
    depends_on:
      - seaweedfs-master
    restart: unless-stopped

  seaweedfs-filer:
    image: chrislusf/seaweedfs:latest
    command: filer -master=seaweedfs-master:9333 -port=8888 -ip=seaweedfs-filer
    ports:
      - "8888:8888"
    volumes:
      - seaweedfs-filer-data:/data
    networks:
      - praktikai
    depends_on:
      - seaweedfs-master
      - seaweedfs-volume
    restart: unless-stopped

volumes:
  minio-data:
  postgres-data:
  seaweedfs-master-data:
  seaweedfs-volume-data:
  seaweedfs-filer-data:

networks:
  praktikai:
    driver: bridge
