-- Migration: 0002 - Kompletní změny od posledního pushe frantisekpetricek (d1f773c, 29.09. 15:07)
-- Samostatný a idempotentní skript (lze pustit opakovaně; na DB s aplikovanou 0002/0003 je to no-op).
-- Obsahuje vše, co jinak vytváří až start aplikace
-- (nové tabulky a jejich seed), takže nezáleží na pořadí "deploy -> migrace".
--
-- Obsah:
--   A) nové tabulky: neuro_principle, krauu_competence, bloom_level, cross_subject
--      a vazební module_neuro_principle, course_krauu_competence, module_krauu_competence,
--      course_bloom_level, module_bloom_level, course_cross_subject
--   B) seed nových číselníků (jen do prázdných tabulek)
--   C) course: sloupce course_requirement_id / course_eqf_level_id / course_type_id (z 0002),
--      course_block_id nepovinný
--   D) course_block: kódy a/b/c -> blok.a/blok.b/blok.c
--   E) module: sloupec perex
--   F) backfill: každý existující modul dostane výchozí neurovědní princip NP-01
--
-- Předpoklad: existují tabulky course, module, course_block, course_eqf_level, course_type,
--             course_requirement (vznikly už dřívějším nasazením) a course_eqf_level obsahuje
--             kód '7', course_type kód 'type.obecny' (výchozí hodnoty pro backfill kurzů).

-- ─── A) NOVÉ TABULKY (idempotentní) ──────────────────────────
CREATE TABLE IF NOT EXISTS neuro_principle (
	principle_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1), 
	code VARCHAR(10) NOT NULL, 
	name VARCHAR(200) NOT NULL, 
	description VARCHAR(255) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	is_active BOOLEAN NOT NULL, 
	PRIMARY KEY (principle_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_neuro_principle_code_active ON neuro_principle (code) WHERE is_active;

CREATE TABLE IF NOT EXISTS krauu_competence (
	krauu_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1), 
	parent_id BIGINT, 
	code VARCHAR(10) NOT NULL, 
	name VARCHAR(200) NOT NULL, 
	description VARCHAR(255) DEFAULT '' NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	is_active BOOLEAN NOT NULL, 
	PRIMARY KEY (krauu_id), 
	FOREIGN KEY(parent_id) REFERENCES krauu_competence (krauu_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_krauu_competence_code_active ON krauu_competence (code) WHERE is_active;

CREATE TABLE IF NOT EXISTS bloom_level (
	bloom_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1), 
	code VARCHAR(10) NOT NULL, 
	name VARCHAR(200) NOT NULL, 
	description VARCHAR(255) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	is_active BOOLEAN NOT NULL, 
	PRIMARY KEY (bloom_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_bloom_level_code_active ON bloom_level (code) WHERE is_active;

CREATE TABLE IF NOT EXISTS cross_subject (
	cross_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1), 
	code VARCHAR(10) NOT NULL, 
	name VARCHAR(200) NOT NULL, 
	description VARCHAR(255) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	is_active BOOLEAN NOT NULL, 
	PRIMARY KEY (cross_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_cross_subject_code_active ON cross_subject (code) WHERE is_active;

CREATE TABLE IF NOT EXISTS module_neuro_principle (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1), 
	module_id BIGINT NOT NULL, 
	principle_id BIGINT NOT NULL, 
	added_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	is_active BOOLEAN NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(module_id) REFERENCES module (module_id), 
	FOREIGN KEY(principle_id) REFERENCES neuro_principle (principle_id)
);

CREATE INDEX IF NOT EXISTS ix_module_neuro_principle_module_id ON module_neuro_principle (module_id);
CREATE INDEX IF NOT EXISTS ix_module_neuro_principle_principle_id ON module_neuro_principle (principle_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_module_neuro_principle ON module_neuro_principle (module_id, principle_id);

CREATE TABLE IF NOT EXISTS course_krauu_competence (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1), 
	course_id BIGINT NOT NULL, 
	krauu_id BIGINT NOT NULL, 
	added_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	is_active BOOLEAN NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(course_id) REFERENCES course (course_id), 
	FOREIGN KEY(krauu_id) REFERENCES krauu_competence (krauu_id)
);

CREATE INDEX IF NOT EXISTS ix_course_krauu_competence_course_id ON course_krauu_competence (course_id);
CREATE INDEX IF NOT EXISTS ix_course_krauu_competence_krauu_id ON course_krauu_competence (krauu_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_course_krauu_competence ON course_krauu_competence (course_id, krauu_id);

CREATE TABLE IF NOT EXISTS module_krauu_competence (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1), 
	module_id BIGINT NOT NULL, 
	krauu_id BIGINT NOT NULL, 
	added_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	is_active BOOLEAN NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(module_id) REFERENCES module (module_id), 
	FOREIGN KEY(krauu_id) REFERENCES krauu_competence (krauu_id)
);

CREATE INDEX IF NOT EXISTS ix_module_krauu_competence_krauu_id ON module_krauu_competence (krauu_id);
CREATE INDEX IF NOT EXISTS ix_module_krauu_competence_module_id ON module_krauu_competence (module_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_module_krauu_competence ON module_krauu_competence (module_id, krauu_id);

CREATE TABLE IF NOT EXISTS course_bloom_level (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1), 
	course_id BIGINT NOT NULL, 
	bloom_id BIGINT NOT NULL, 
	added_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	is_active BOOLEAN NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(course_id) REFERENCES course (course_id), 
	FOREIGN KEY(bloom_id) REFERENCES bloom_level (bloom_id)
);

CREATE INDEX IF NOT EXISTS ix_course_bloom_level_bloom_id ON course_bloom_level (bloom_id);
CREATE INDEX IF NOT EXISTS ix_course_bloom_level_course_id ON course_bloom_level (course_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_course_bloom_level ON course_bloom_level (course_id, bloom_id);

CREATE TABLE IF NOT EXISTS module_bloom_level (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1), 
	module_id BIGINT NOT NULL, 
	bloom_id BIGINT NOT NULL, 
	added_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	is_active BOOLEAN NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(module_id) REFERENCES module (module_id), 
	FOREIGN KEY(bloom_id) REFERENCES bloom_level (bloom_id)
);

CREATE INDEX IF NOT EXISTS ix_module_bloom_level_bloom_id ON module_bloom_level (bloom_id);
CREATE INDEX IF NOT EXISTS ix_module_bloom_level_module_id ON module_bloom_level (module_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_module_bloom_level ON module_bloom_level (module_id, bloom_id);

CREATE TABLE IF NOT EXISTS course_cross_subject (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1), 
	course_id BIGINT NOT NULL, 
	cross_id BIGINT NOT NULL, 
	added_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	is_active BOOLEAN NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(course_id) REFERENCES course (course_id), 
	FOREIGN KEY(cross_id) REFERENCES cross_subject (cross_id)
);

CREATE INDEX IF NOT EXISTS ix_course_cross_subject_course_id ON course_cross_subject (course_id);
CREATE INDEX IF NOT EXISTS ix_course_cross_subject_cross_id ON course_cross_subject (cross_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_course_cross_subject ON course_cross_subject (course_id, cross_id);

-- ─── B) SEED DAT (jen když je tabulka prázdná, stejně jako seed_db) ─
INSERT INTO neuro_principle (code, name, description, is_active)
SELECT * FROM (VALUES
  ('NP-01', 'Neuroplasticita', 'Opakované učení mění strukturu synaptických sítí v mozku', true),
  ('NP-02', 'Distribuované opakování', 'Učení rozložené v čase vede k trvalejšímu zapamatování', true),
  ('NP-03', 'Aktivní vybavování', 'Vědomé vybavování z paměti posiluje stopu víc než pasivní', true),
  ('NP-04', 'Žádoucí obtíže', 'Mírná obtížnost a kognitivní zápas prohlubují zpracování a', true),
  ('NP-05', 'Prokládání', 'Střídání různých typů úloh podporuje rozlišování konceptů', true),
  ('NP-06', 'Duální kódování', 'Kombinace verbální a vizuální reprezentace vytváří dvě', true),
  ('NP-07', 'Kognitivní zátěž', 'Pracovní paměť má kapacitu cca 4 ± 1 prvků; přetížení', true),
  ('NP-08', 'Elaborativní kódování', 'Propojení nové informace s existujícími znalostmi tvoří síť', true),
  ('NP-09', 'Efekt generování', 'Sám vytvořená informace se pamatuje lépe než pasivně', true),
  ('NP-10', 'Testovací efekt', 'Samotné testování konsoliduje dlouhodobou paměť silněji', true),
  ('NP-11', 'Predikční chyba', 'Dopaminový systém reaguje na rozdíl mezi očekáváním a', true),
  ('NP-12', 'Konsolidace ve spánku', 'Spánek přepisuje paměťové stopy z hipokampu do', true),
  ('NP-13', 'Pozornost a pracovní paměť', 'Bez selektivní pozornosti nedochází ke kódování', true),
  ('NP-14', 'Slučování do bloků', 'Sdružování informací do smysluplných bloků zvyšuje', true),
  ('NP-15', 'Metakognice', 'Schopnost přemýšlet o vlastním myšlení a sledovat', true),
  ('NP-16', 'Zrcadlové neurony', 'Pozorování postupu druhého aktivuje stejné okruhy jako', true),
  ('NP-17', 'Stav plynutí (flow)', 'Optimální poměr výzvy a dovednosti maximalizuje zapojení', true),
  ('NP-18', 'Okamžitá zpětná vazba', 'Rychlá konkrétní zpětná vazba umožní opravit chybu dřív', true),
  ('NP-19', 'Vtělené poznávání', 'Tělesné zapojení (gesta, řeč nahlas, kreslení) posiluje', true),
  ('NP-20', 'Schémata', 'Nové informace se snáze ukládají při napojení na existující', true)
) AS v(code, name, description, is_active)
WHERE NOT EXISTS (SELECT 1 FROM neuro_principle);

INSERT INTO bloom_level (code, name, description, is_active)
SELECT * FROM (VALUES
  ('1', 'Zapamatovat', 'vyjmenuje, popíše, identifikuje, rozpozná, zopakuje', true),
  ('2', 'Porozumět', 'vysvětlí, shrne, klasifikuje, interpretuje, přeloží', true),
  ('3', 'Aplikovat', 'použije, provede, řeší, demonstruje, implementuje', true),
  ('4', 'Analyzovat', 'porovná, rozliší, zhodnotí strukturu, rozloží, prozkoumá', true),
  ('5', 'Hodnotit', 'posoudí, obhájí, kriticky zhodnotí, doporučí, zdůvodní', true),
  ('6', 'Tvořit', 'navrhne, sestaví, vytvoří, zkonstruuje, naplánuje', true)
) AS v(code, name, description, is_active)
WHERE NOT EXISTS (SELECT 1 FROM bloom_level);

INSERT INTO cross_subject (code, name, description, is_active)
SELECT * FROM (VALUES
  ('O001', 'AI gramotnost – technický základ', 'Jak fungují jazykové modely, tokeny, kontextové okno, pravděpodobnostní povaha výstupu.', true),
  ('O002', 'AI gramotnost – kritické posuzování výstupů', 'Rozpoznávání halucinací, ověřování faktů, srovnávání nástrojů a výstupů.', true),
  ('O003', 'Etika a odpovědné využití AI', 'Etické principy práce s AI ve vzdělávání, hranice akceptovatelného použití, transparentnost.', true),
  ('O004', 'Ochrana dat a soukromí ve výuce', 'GDPR, citlivá data žáků, bezpečné nakládání s informacemi v AI nástrojích.', true),
  ('O005', 'Rozvoj kritického myšlení', 'Vedení žáků ke kritickému uvažování, argumentaci, posuzování zdrojů — s podporou i navzdory AI.', true),
  ('O006', 'Metakognice a seberízené učení', 'Reflexe vlastního učení, uvědomování si procesu poznávání, strategie učení.', true),
  ('O007', 'Plánování výuky a tvorba scénářů', 'Návrh výukových jednotek, cíle, aktivity, role AI ve scénáři, časové rozvržení.', true),
  ('O008', 'Didaktická transformace obsahu', 'Převod oborového obsahu do podoby srozumitelné pro žáky daného stupně.', true),
  ('O009', 'Diferenciace a inkluze (žáci se SVP)', 'Práce s heterogenní třídou, individuální vzdělávací plány, AI jako podpora diferenciace.', true),
  ('O010', 'Hodnocení a zpětná vazba', 'Formativní i sumativní hodnocení, kvalitní zpětná vazba, rubriky, AI jako asistent hodnocení.', true),
  ('O011', 'Tvorba zadání a úloh (AI-resistant + AI-supported)', 'Design zadání odolných vůči zneužití AI a zároveň zadání využívajících AI jako nástroj učení.', true),
  ('O012', 'Práce s prekoncepty a miskoncepty', 'Diagnostika a práce s chybnými představami žáků, AI jako nástroj odhalování miskonceptů.', true),
  ('O013', 'Prostředí pro učení a klima třídy', 'Bezpečné prostředí, pravidla práce s AI ve třídě, kultura ne/používání AI.', true),
  ('O014', 'Motivace a vedení žáků', 'Vnitřní motivace, vedení diskuse, zapojování žáků, AI jako nástroj individualizace motivace.', true),
  ('O015', 'Komunikace s rodiči a zákonnými zástupci', 'Vysvětlování role AI ve výuce rodičům, řešení obav, společná dohoda o pravidlech.', true),
  ('O016', 'Profesní spolupráce a kolegiální učení', 'Sdílení dobré praxe, peer review, budování AI-gramotné školy jako celku.', true),
  ('O017', 'Mentoring a uvádění začínajících', 'Provázení nastupujících kolegů, mentorský dialog, integrace', true),
  ('O018', 'Profesní sebepojetí a reflexe vlastní', 'Vlastní identita učitele v éře AI, reflektivní praxe, profesní', true),
  ('O019', 'Duševní zdraví a wellbeing učitele', 'Práce s kognitivní zátěží, využití AI pro snížení', true),
  ('O020', 'Tvořivost a designové myšlení ve', 'Tvořivé využití AI při návrhu výukových materiálů, design', true)
) AS v(code, name, description, is_active)
WHERE NOT EXISTS (SELECT 1 FROM cross_subject);

INSERT INTO krauu_competence (code, name, description, is_active)
SELECT * FROM (VALUES
  ('1.0', 'Oblast 1 – Obsah a didaktika', '', true),
  ('2.0', 'Oblast 2 – Plánování, vedení a reflexe výuky', '', true),
  ('3.0', 'Oblast 3 – Prostředí pro učení', '', true),
  ('4.0', 'Oblast 4 – Zpětná vazba a hodnocení', '', true),
  ('5.0', 'Oblast 5 – Profesní spolupráce', '', true),
  ('6.0', 'Oblast 6 – Profesní sebepojetí, rozvoj, etika a duševní zdraví', '', true)
) AS v(code, name, description, is_active)
WHERE NOT EXISTS (SELECT 1 FROM krauu_competence);

INSERT INTO krauu_competence (code, name, description, parent_id, is_active)
SELECT v.code, v.name, v.description, p.krauu_id, v.is_active FROM (VALUES
  ('1.1', 'Rozumí vyučovaným oborům a rozvíjí', 'Učitel/ka rozumí oborům, které vyučuje, a systematicky se', '1.0', true),
  ('1.2', 'Didakticky zprostředkovává obsah', 'Zprostředkovává obsah žákům v souladu s jejich', '1.0', true),
  ('2.1', 'Nastavuje cíle výuky', 'Stanovuje srozumitelné cíle a vede k jejich nastavování i', '2.0', true),
  ('2.2', 'Poznává vzdělávací potřeby a plánuje', 'Plánuje výuku tak, aby každý žák mohl aktivně dosahovat', '2.0', true),
  ('2.3', 'Podporuje zvídavost a motivaci žáků', 'Podporuje u žáků zvídavost a motivaci k učení.', '2.0', true),
  ('2.4', 'Efektivně vede výuku a zjišťuje', 'Vede výuku efektivně, zjišťuje porozumění a reaguje na', '2.0', true),
  ('2.5', 'Reflektuje výuku', 'Reflektuje vlastní výuku a vyhodnocuje dosahování cílů.', '2.0', true),
  ('3.1', 'Vytváří bezpečné prostředí pro učení', 'Vytváří fyzicky i psychicky bezpečné prostředí pro učení.', '3.0', true),
  ('3.2', 'Vede žáky k chování podporujícímu', 'Vede žáky k chování podporujícímu vlastní učení i', '3.0', true),
  ('3.3', 'Uspořádání fyzického a digitálního', 'Zajišťuje vhodné uspořádání fyzického a digitálního', '3.0', true),
  ('4.1', 'Hodnotí na základě kritérií', 'Hodnotí žáky na základě jasných kritérií a vede k tomu i', '4.0', true),
  ('4.2', 'Poskytuje a přijímá zpětnou vazbu', 'Poskytuje žákům konstruktivní zpětnou vazbu a sám přijímá', '4.0', true),
  ('4.3', 'Vede žáky k reflexi jejich učení', 'Vede žáky k reflexi vlastního učení a samostatné', '4.0', true),
  ('5.1', 'Spolupracuje s kolegy a kolegyněmi', 'Spolupracuje s kolegy ve prospěch žáků a společného', '5.0', true),
  ('5.2', 'Spolupracuje s rodiči a širší', 'Spolupracuje s rodiči a širší komunitou v zájmu žáků.', '5.0', true),
  ('6.1', 'Utváření profesního sebepojetí a', 'Systematicky pracuje na utváření profesního sebepojetí a', '6.0', true),
  ('6.2', 'Odpovědná práce s informacemi a', 'Odpovědně pracuje s informacemi a digitálními nástroji,', '6.0', true),
  ('6.3', 'Duševní zdraví a psychohygiena', 'Systematicky pečuje o své duševní zdraví a psychohygienu.', '6.0', true)
) AS v(code, name, description, area_code, is_active)
JOIN krauu_competence p ON p.code = v.area_code
WHERE NOT EXISTS (SELECT 1 FROM krauu_competence WHERE parent_id IS NOT NULL);


-- ─── C) COURSE: nové sloupce + nepovinný blok ─────────────────

ALTER TABLE course ADD COLUMN IF NOT EXISTS course_requirement_id BIGINT;
ALTER TABLE course ADD COLUMN IF NOT EXISTS course_eqf_level_id BIGINT;
ALTER TABLE course ADD COLUMN IF NOT EXISTS course_type_id BIGINT;

UPDATE course
SET course_eqf_level_id = (SELECT eqf_level_id FROM course_eqf_level WHERE code = '7' LIMIT 1)
WHERE course_eqf_level_id IS NULL;

UPDATE course
SET course_type_id = (SELECT type_id FROM course_type WHERE code = 'type.obecny' LIMIT 1)
WHERE course_type_id IS NULL;

ALTER TABLE course
    ALTER COLUMN course_eqf_level_id SET NOT NULL,
    ALTER COLUMN course_type_id SET NOT NULL;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'course_course_requirement_id_fkey') THEN
        ALTER TABLE course ADD CONSTRAINT course_course_requirement_id_fkey
            FOREIGN KEY (course_requirement_id) REFERENCES course_requirement(requirement_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'course_course_eqf_level_id_fkey') THEN
        ALTER TABLE course ADD CONSTRAINT course_course_eqf_level_id_fkey
            FOREIGN KEY (course_eqf_level_id) REFERENCES course_eqf_level(eqf_level_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'course_course_type_id_fkey') THEN
        ALTER TABLE course ADD CONSTRAINT course_course_type_id_fkey
            FOREIGN KEY (course_type_id) REFERENCES course_type(type_id);
    END IF;
END $$;

ALTER TABLE course ALTER COLUMN course_block_id DROP NOT NULL;

-- ─── D) COURSE_BLOCK: přejmenování kódů ───────────────────────

UPDATE course_block SET code = 'blok.a' WHERE code = 'a';
UPDATE course_block SET code = 'blok.b' WHERE code = 'b';
UPDATE course_block SET code = 'blok.c' WHERE code = 'c';

-- ─── E) MODULE: perex ─────────────────────────────────────────

ALTER TABLE module ADD COLUMN IF NOT EXISTS perex VARCHAR(255) NOT NULL DEFAULT '';

-- ─── F) BACKFILL: výchozí neurovědní princip pro existující moduly ─

INSERT INTO module_neuro_principle (module_id, principle_id, is_active)
SELECT m.module_id, (SELECT principle_id FROM neuro_principle WHERE code = 'NP-01' LIMIT 1), true
FROM module m
WHERE NOT EXISTS (
    SELECT 1 FROM module_neuro_principle mnp
    WHERE mnp.module_id = m.module_id AND mnp.is_active = true
);
