-- Migration: 0004 - Public resource KRAUU kompetence a Bloomova taxonomie
-- Description: Vazební tabulky (M2M) pub_resource ↔ krauu_competence a pub_resource ↔ bloom_level.
-- Requires existing tables: pub_resource, krauu_competence, bloom_level (migrace 0002)

CREATE TABLE IF NOT EXISTS pub_resource_krauu_competence (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
	resource_id BIGINT NOT NULL,
	krauu_id BIGINT NOT NULL,
	added_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	is_active BOOLEAN NOT NULL DEFAULT true,
	PRIMARY KEY (id),
	FOREIGN KEY(resource_id) REFERENCES pub_resource (resource_id),
	FOREIGN KEY(krauu_id) REFERENCES krauu_competence (krauu_id)
);

CREATE INDEX IF NOT EXISTS ix_pub_resource_krauu_competence_resource_id ON pub_resource_krauu_competence (resource_id);
CREATE INDEX IF NOT EXISTS ix_pub_resource_krauu_competence_krauu_id ON pub_resource_krauu_competence (krauu_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_pub_resource_krauu_competence ON pub_resource_krauu_competence (resource_id, krauu_id);

CREATE TABLE IF NOT EXISTS pub_resource_bloom_level (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
	resource_id BIGINT NOT NULL,
	bloom_id BIGINT NOT NULL,
	added_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	is_active BOOLEAN NOT NULL DEFAULT true,
	PRIMARY KEY (id),
	FOREIGN KEY(resource_id) REFERENCES pub_resource (resource_id),
	FOREIGN KEY(bloom_id) REFERENCES bloom_level (bloom_id)
);

CREATE INDEX IF NOT EXISTS ix_pub_resource_bloom_level_resource_id ON pub_resource_bloom_level (resource_id);
CREATE INDEX IF NOT EXISTS ix_pub_resource_bloom_level_bloom_id ON pub_resource_bloom_level (bloom_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_pub_resource_bloom_level ON pub_resource_bloom_level (resource_id, bloom_id);
