/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ActivityKind } from './ActivityKind';
import {
    ActivityKindFromJSON,
    ActivityKindFromJSONTyped,
    ActivityKindToJSON,
    ActivityKindToJSONTyped,
} from './ActivityKind';

/**
 * 
 * @export
 * @interface ActivityCreate
 */
export interface ActivityCreate {
    /**
     * 
     * @type {string}
     * @memberof ActivityCreate
     */
    title: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ActivityCreate
     */
    content?: { [key: string]: any; } | null;
    /**
     * Pořadí aktivit v rámci modulu (>= 1)
     * @type {number}
     * @memberof ActivityCreate
     */
    order?: number;
    /**
     * 
     * @type {ActivityKind}
     * @memberof ActivityCreate
     */
    kind?: ActivityKind;
    /**
     * FK na module.module_id
     * @type {number}
     * @memberof ActivityCreate
     */
    moduleId: number;
}



/**
 * Check if a given object implements the ActivityCreate interface.
 */
export function instanceOfActivityCreate(value: object): value is ActivityCreate {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('moduleId' in value) || value['moduleId'] === undefined) return false;
    return true;
}

export function ActivityCreateFromJSON(json: any): ActivityCreate {
    return ActivityCreateFromJSONTyped(json, false);
}

export function ActivityCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivityCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'content': json['content'] == null ? undefined : json['content'],
        'order': json['order'] == null ? undefined : json['order'],
        'kind': json['kind'] == null ? undefined : ActivityKindFromJSON(json['kind']),
        'moduleId': json['module_id'],
    };
}

export function ActivityCreateToJSON(json: any): ActivityCreate {
    return ActivityCreateToJSONTyped(json, false);
}

export function ActivityCreateToJSONTyped(value?: ActivityCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'content': value['content'],
        'order': value['order'],
        'kind': ActivityKindToJSON(value['kind']),
        'module_id': value['moduleId'],
    };
}

