/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ActivityKind } from './ActivityKind';
import {
    ActivityKindFromJSON,
    ActivityKindFromJSONTyped,
    ActivityKindToJSON,
    ActivityKindToJSONTyped,
} from './ActivityKind';

/**
 * 
 * @export
 * @interface Activity
 */
export interface Activity {
    /**
     * 
     * @type {string}
     * @memberof Activity
     */
    title: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof Activity
     */
    content?: { [key: string]: any; } | null;
    /**
     * Pořadí aktivit v rámci modulu (>= 1)
     * @type {number}
     * @memberof Activity
     */
    order?: number;
    /**
     * 
     * @type {ActivityKind}
     * @memberof Activity
     */
    kind?: ActivityKind;
    /**
     * 
     * @type {number}
     * @memberof Activity
     */
    activityId: number;
    /**
     * 
     * @type {number}
     * @memberof Activity
     */
    moduleId: number;
    /**
     * 
     * @type {boolean}
     * @memberof Activity
     */
    isActive: boolean;
}



/**
 * Check if a given object implements the Activity interface.
 */
export function instanceOfActivity(value: object): value is Activity {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('activityId' in value) || value['activityId'] === undefined) return false;
    if (!('moduleId' in value) || value['moduleId'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    return true;
}

export function ActivityFromJSON(json: any): Activity {
    return ActivityFromJSONTyped(json, false);
}

export function ActivityFromJSONTyped(json: any, ignoreDiscriminator: boolean): Activity {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'content': json['content'] == null ? undefined : json['content'],
        'order': json['order'] == null ? undefined : json['order'],
        'kind': json['kind'] == null ? undefined : ActivityKindFromJSON(json['kind']),
        'activityId': json['activity_id'],
        'moduleId': json['module_id'],
        'isActive': json['is_active'],
    };
}

export function ActivityToJSON(json: any): Activity {
    return ActivityToJSONTyped(json, false);
}

export function ActivityToJSONTyped(value?: Activity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'content': value['content'],
        'order': value['order'],
        'kind': ActivityKindToJSON(value['kind']),
        'activity_id': value['activityId'],
        'module_id': value['moduleId'],
        'is_active': value['isActive'],
    };
}

