/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ActivityKind = {
    Learn: 'learn',
    Practice: 'practice',
    Assessment: 'assessment'
} as const;
export type ActivityKind = typeof ActivityKind[keyof typeof ActivityKind];


export function instanceOfActivityKind(value: any): boolean {
    for (const key in ActivityKind) {
        if (Object.prototype.hasOwnProperty.call(ActivityKind, key)) {
            if (ActivityKind[key as keyof typeof ActivityKind] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ActivityKindFromJSON(json: any): ActivityKind {
    return ActivityKindFromJSONTyped(json, false);
}

export function ActivityKindFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivityKind {
    return json as ActivityKind;
}

export function ActivityKindToJSON(value?: ActivityKind | null): any {
    return value as any;
}

export function ActivityKindToJSONTyped(value: any, ignoreDiscriminator: boolean): ActivityKind {
    return value as ActivityKind;
}

