/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CourseLink } from './CourseLink';
import {
    CourseLinkFromJSON,
    CourseLinkFromJSONTyped,
    CourseLinkToJSON,
    CourseLinkToJSONTyped,
} from './CourseLink';
import type { Status } from './Status';
import {
    StatusFromJSON,
    StatusFromJSONTyped,
    StatusToJSON,
    StatusToJSONTyped,
} from './Status';
import type { CourseFile } from './CourseFile';
import {
    CourseFileFromJSON,
    CourseFileFromJSONTyped,
    CourseFileToJSON,
    CourseFileToJSONTyped,
} from './CourseFile';
import type { Module } from './Module';
import {
    ModuleFromJSON,
    ModuleFromJSONTyped,
    ModuleToJSON,
    ModuleToJSONTyped,
} from './Module';

/**
 * 
 * @export
 * @interface Course
 */
export interface Course {
    /**
     * 
     * @type {string}
     * @memberof Course
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Course
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Course
     */
    modulesCount?: number;
    /**
     * 
     * @type {number}
     * @memberof Course
     */
    courseId: number;
    /**
     * 
     * @type {boolean}
     * @memberof Course
     */
    isActive: boolean;
    /**
     * 
     * @type {Status}
     * @memberof Course
     */
    status: Status;
    /**
     * 
     * @type {string}
     * @memberof Course
     */
    summary?: string | null;
    /**
     * 
     * @type {Array<Module>}
     * @memberof Course
     */
    modules?: Array<Module>;
    /**
     * 
     * @type {Array<CourseFile>}
     * @memberof Course
     */
    files?: Array<CourseFile>;
    /**
     * 
     * @type {Array<CourseLink>}
     * @memberof Course
     */
    links?: Array<CourseLink>;
}



/**
 * Check if a given object implements the Course interface.
 */
export function instanceOfCourse(value: object): value is Course {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('courseId' in value) || value['courseId'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function CourseFromJSON(json: any): Course {
    return CourseFromJSONTyped(json, false);
}

export function CourseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Course {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'modulesCount': json['modules_count'] == null ? undefined : json['modules_count'],
        'courseId': json['course_id'],
        'isActive': json['is_active'],
        'status': StatusFromJSON(json['status']),
        'summary': json['summary'] == null ? undefined : json['summary'],
        'modules': json['modules'] == null ? undefined : ((json['modules'] as Array<any>).map(ModuleFromJSON)),
        'files': json['files'] == null ? undefined : ((json['files'] as Array<any>).map(CourseFileFromJSON)),
        'links': json['links'] == null ? undefined : ((json['links'] as Array<any>).map(CourseLinkFromJSON)),
    };
}

export function CourseToJSON(json: any): Course {
    return CourseToJSONTyped(json, false);
}

export function CourseToJSONTyped(value?: Course | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'modules_count': value['modulesCount'],
        'course_id': value['courseId'],
        'is_active': value['isActive'],
        'status': StatusToJSON(value['status']),
        'summary': value['summary'],
        'modules': value['modules'] == null ? undefined : ((value['modules'] as Array<any>).map(ModuleToJSON)),
        'files': value['files'] == null ? undefined : ((value['files'] as Array<any>).map(CourseFileToJSON)),
        'links': value['links'] == null ? undefined : ((value['links'] as Array<any>).map(CourseLinkToJSON)),
    };
}

