/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CourseCreate
 */
export interface CourseCreate {
    /**
     * 
     * @type {string}
     * @memberof CourseCreate
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof CourseCreate
     */
    description?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof CourseCreate
     */
    isPublished?: boolean;
}

/**
 * Check if a given object implements the CourseCreate interface.
 */
export function instanceOfCourseCreate(value: object): value is CourseCreate {
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function CourseCreateFromJSON(json: any): CourseCreate {
    return CourseCreateFromJSONTyped(json, false);
}

export function CourseCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'isPublished': json['is_published'] == null ? undefined : json['is_published'],
    };
}

export function CourseCreateToJSON(json: any): CourseCreate {
    return CourseCreateToJSONTyped(json, false);
}

export function CourseCreateToJSONTyped(value?: CourseCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'is_published': value['isPublished'],
    };
}

