/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CourseUpdate
 */
export interface CourseUpdate {
    /**
     * 
     * @type {string}
     * @memberof CourseUpdate
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof CourseUpdate
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CourseUpdate
     */
    modulesCount?: number;
}

/**
 * Check if a given object implements the CourseUpdate interface.
 */
export function instanceOfCourseUpdate(value: object): value is CourseUpdate {
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function CourseUpdateFromJSON(json: any): CourseUpdate {
    return CourseUpdateFromJSONTyped(json, false);
}

export function CourseUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'modulesCount': json['modules_count'] == null ? undefined : json['modules_count'],
    };
}

export function CourseUpdateToJSON(json: any): CourseUpdate {
    return CourseUpdateToJSONTyped(json, false);
}

export function CourseUpdateToJSONTyped(value?: CourseUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'modules_count': value['modulesCount'],
    };
}

