/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Schema pro soubor kurzu
 * @export
 * @interface CourseFile
 */
export interface CourseFile {
    /**
     * 
     * @type {number}
     * @memberof CourseFile
     */
    fileId: number;
    /**
     * 
     * @type {number}
     * @memberof CourseFile
     */
    courseId: number;
    /**
     * 
     * @type {string}
     * @memberof CourseFile
     */
    filename: string;
    /**
     * 
     * @type {string}
     * @memberof CourseFile
     */
    filePath: string;
}

/**
 * Check if a given object implements the CourseFile interface.
 */
export function instanceOfCourseFile(value: object): value is CourseFile {
    if (!('fileId' in value) || value['fileId'] === undefined) return false;
    if (!('courseId' in value) || value['courseId'] === undefined) return false;
    if (!('filename' in value) || value['filename'] === undefined) return false;
    if (!('filePath' in value) || value['filePath'] === undefined) return false;
    return true;
}

export function CourseFileFromJSON(json: any): CourseFile {
    return CourseFileFromJSONTyped(json, false);
}

export function CourseFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseFile {
    if (json == null) {
        return json;
    }
    return {
        
        'fileId': json['file_id'],
        'courseId': json['course_id'],
        'filename': json['filename'],
        'filePath': json['file_path'],
    };
}

export function CourseFileToJSON(json: any): CourseFile {
    return CourseFileToJSONTyped(json, false);
}

export function CourseFileToJSONTyped(value?: CourseFile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'file_id': value['fileId'],
        'course_id': value['courseId'],
        'filename': value['filename'],
        'file_path': value['filePath'],
    };
}

