/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Module } from './Module';
import {
    ModuleFromJSON,
    ModuleFromJSONTyped,
    ModuleToJSON,
    ModuleToJSONTyped,
} from './Module';

/**
 * 
 * @export
 * @interface Course
 */
export interface Course {
    /**
     * 
     * @type {string}
     * @memberof Course
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Course
     */
    description?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof Course
     */
    isPublished?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Course
     */
    courseId: number;
    /**
     * 
     * @type {boolean}
     * @memberof Course
     */
    isActive: boolean;
    /**
     * 
     * @type {Array<Module>}
     * @memberof Course
     */
    modules: Array<Module>;
}

/**
 * Check if a given object implements the Course interface.
 */
export function instanceOfCourse(value: object): value is Course {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('courseId' in value) || value['courseId'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    if (!('modules' in value) || value['modules'] === undefined) return false;
    return true;
}

export function CourseFromJSON(json: any): Course {
    return CourseFromJSONTyped(json, false);
}

export function CourseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Course {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'isPublished': json['is_published'] == null ? undefined : json['is_published'],
        'courseId': json['course_id'],
        'isActive': json['is_active'],
        'modules': ((json['modules'] as Array<any>).map(ModuleFromJSON)),
    };
}

export function CourseToJSON(json: any): Course {
    return CourseToJSONTyped(json, false);
}

export function CourseToJSONTyped(value?: Course | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'is_published': value['isPublished'],
        'course_id': value['courseId'],
        'is_active': value['isActive'],
        'modules': ((value['modules'] as Array<any>).map(ModuleToJSON)),
    };
}

