/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Schema pro odkaz kurzu
 * @export
 * @interface CourseLink
 */
export interface CourseLink {
    /**
     * 
     * @type {number}
     * @memberof CourseLink
     */
    linkId: number;
    /**
     * 
     * @type {number}
     * @memberof CourseLink
     */
    courseId: number;
    /**
     * 
     * @type {string}
     * @memberof CourseLink
     */
    url: string;
}

/**
 * Check if a given object implements the CourseLink interface.
 */
export function instanceOfCourseLink(value: object): value is CourseLink {
    if (!('linkId' in value) || value['linkId'] === undefined) return false;
    if (!('courseId' in value) || value['courseId'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function CourseLinkFromJSON(json: any): CourseLink {
    return CourseLinkFromJSONTyped(json, false);
}

export function CourseLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseLink {
    if (json == null) {
        return json;
    }
    return {
        
        'linkId': json['link_id'],
        'courseId': json['course_id'],
        'url': json['url'],
    };
}

export function CourseLinkToJSON(json: any): CourseLink {
    return CourseLinkToJSONTyped(json, false);
}

export function CourseLinkToJSONTyped(value?: CourseLink | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link_id': value['linkId'],
        'course_id': value['courseId'],
        'url': value['url'],
    };
}

