/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response s vygenerovaným kurzem
 * @export
 * @interface GenerateCourseResponse
 */
export interface GenerateCourseResponse {
    /**
     * 
     * @type {string}
     * @memberof GenerateCourseResponse
     */
    title: string;
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof GenerateCourseResponse
     */
    modules: Array<{ [key: string]: any; }>;
}

/**
 * Check if a given object implements the GenerateCourseResponse interface.
 */
export function instanceOfGenerateCourseResponse(value: object): value is GenerateCourseResponse {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('modules' in value) || value['modules'] === undefined) return false;
    return true;
}

export function GenerateCourseResponseFromJSON(json: any): GenerateCourseResponse {
    return GenerateCourseResponseFromJSONTyped(json, false);
}

export function GenerateCourseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateCourseResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'modules': json['modules'],
    };
}

export function GenerateCourseResponseToJSON(json: any): GenerateCourseResponse {
    return GenerateCourseResponseToJSONTyped(json, false);
}

export function GenerateCourseResponseToJSONTyped(value?: GenerateCourseResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'modules': value['modules'],
    };
}

