/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModuleUpdate
 */
export interface ModuleUpdate {
    /**
     * 
     * @type {string}
     * @memberof ModuleUpdate
     */
    title: string;
    /**
     * Pořadí modulu v rámci kurzu (>= 1)
     * @type {number}
     * @memberof ModuleUpdate
     */
    order?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ModuleUpdate
     */
    isActive?: boolean;
    /**
     * Je modul publikován?
     * @type {boolean}
     * @memberof ModuleUpdate
     */
    isPublished?: boolean;
}

/**
 * Check if a given object implements the ModuleUpdate interface.
 */
export function instanceOfModuleUpdate(value: object): value is ModuleUpdate {
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function ModuleUpdateFromJSON(json: any): ModuleUpdate {
    return ModuleUpdateFromJSONTyped(json, false);
}

export function ModuleUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModuleUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'order': json['order'] == null ? undefined : json['order'],
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
        'isPublished': json['is_published'] == null ? undefined : json['is_published'],
    };
}

export function ModuleUpdateToJSON(json: any): ModuleUpdate {
    return ModuleUpdateToJSONTyped(json, false);
}

export function ModuleUpdateToJSONTyped(value?: ModuleUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'order': value['order'],
        'is_active': value['isActive'],
        'is_published': value['isPublished'],
    };
}

