/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModuleCreate
 */
export interface ModuleCreate {
    /**
     * 
     * @type {string}
     * @memberof ModuleCreate
     */
    title: string;
    /**
     * Pořadí modulu v rámci kurzu (>= 1)
     * @type {number}
     * @memberof ModuleCreate
     */
    order?: number;
    /**
     * FK na course.course_id
     * @type {number}
     * @memberof ModuleCreate
     */
    courseId: number;
}

/**
 * Check if a given object implements the ModuleCreate interface.
 */
export function instanceOfModuleCreate(value: object): value is ModuleCreate {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('courseId' in value) || value['courseId'] === undefined) return false;
    return true;
}

export function ModuleCreateFromJSON(json: any): ModuleCreate {
    return ModuleCreateFromJSONTyped(json, false);
}

export function ModuleCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModuleCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'order': json['order'] == null ? undefined : json['order'],
        'courseId': json['course_id'],
    };
}

export function ModuleCreateToJSON(json: any): ModuleCreate {
    return ModuleCreateToJSONTyped(json, false);
}

export function ModuleCreateToJSONTyped(value?: ModuleCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'order': value['order'],
        'course_id': value['courseId'],
    };
}

