/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LearnBlock } from './LearnBlock';
import {
    LearnBlockFromJSON,
    LearnBlockFromJSONTyped,
    LearnBlockToJSON,
    LearnBlockToJSONTyped,
} from './LearnBlock';
import type { Practice } from './Practice';
import {
    PracticeFromJSON,
    PracticeFromJSONTyped,
    PracticeToJSON,
    PracticeToJSONTyped,
} from './Practice';

/**
 * 
 * @export
 * @interface Module
 */
export interface Module {
    /**
     * 
     * @type {string}
     * @memberof Module
     */
    title: string;
    /**
     * Pořadí modulu v rámci kurzu (>= 1)
     * @type {number}
     * @memberof Module
     */
    position?: number;
    /**
     * 
     * @type {number}
     * @memberof Module
     */
    moduleId: number;
    /**
     * 
     * @type {number}
     * @memberof Module
     */
    courseId: number;
    /**
     * 
     * @type {boolean}
     * @memberof Module
     */
    isActive: boolean;
    /**
     * 
     * @type {Date}
     * @memberof Module
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Module
     */
    updatedAt: Date;
    /**
     * 
     * @type {Array<LearnBlock>}
     * @memberof Module
     */
    learnBlocks?: Array<LearnBlock>;
    /**
     * 
     * @type {Array<Practice>}
     * @memberof Module
     */
    practices?: Array<Practice>;
}

/**
 * Check if a given object implements the Module interface.
 */
export function instanceOfModule(value: object): value is Module {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('moduleId' in value) || value['moduleId'] === undefined) return false;
    if (!('courseId' in value) || value['courseId'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ModuleFromJSON(json: any): Module {
    return ModuleFromJSONTyped(json, false);
}

export function ModuleFromJSONTyped(json: any, ignoreDiscriminator: boolean): Module {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'position': json['position'] == null ? undefined : json['position'],
        'moduleId': json['module_id'],
        'courseId': json['course_id'],
        'isActive': json['is_active'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'learnBlocks': json['learn_blocks'] == null ? undefined : ((json['learn_blocks'] as Array<any>).map(LearnBlockFromJSON)),
        'practices': json['practices'] == null ? undefined : ((json['practices'] as Array<any>).map(PracticeFromJSON)),
    };
}

export function ModuleToJSON(json: any): Module {
    return ModuleToJSONTyped(json, false);
}

export function ModuleToJSONTyped(value?: Module | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'position': value['position'],
        'module_id': value['moduleId'],
        'course_id': value['courseId'],
        'is_active': value['isActive'],
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
        'learn_blocks': value['learnBlocks'] == null ? undefined : ((value['learnBlocks'] as Array<any>).map(LearnBlockToJSON)),
        'practices': value['practices'] == null ? undefined : ((value['practices'] as Array<any>).map(PracticeToJSON)),
    };
}

