/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Module
 */
export interface Module {
    /**
     * 
     * @type {string}
     * @memberof Module
     */
    title: string;
    /**
     * Pořadí modulu v rámci kurzu (>= 1)
     * @type {number}
     * @memberof Module
     */
    order?: number;
    /**
     * 
     * @type {number}
     * @memberof Module
     */
    moduleId: number;
    /**
     * 
     * @type {number}
     * @memberof Module
     */
    courseId: number;
    /**
     * 
     * @type {boolean}
     * @memberof Module
     */
    isActive: boolean;
}

/**
 * Check if a given object implements the Module interface.
 */
export function instanceOfModule(value: object): value is Module {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('moduleId' in value) || value['moduleId'] === undefined) return false;
    if (!('courseId' in value) || value['courseId'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    return true;
}

export function ModuleFromJSON(json: any): Module {
    return ModuleFromJSONTyped(json, false);
}

export function ModuleFromJSONTyped(json: any, ignoreDiscriminator: boolean): Module {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'order': json['order'] == null ? undefined : json['order'],
        'moduleId': json['module_id'],
        'courseId': json['course_id'],
        'isActive': json['is_active'],
    };
}

export function ModuleToJSON(json: any): Module {
    return ModuleToJSONTyped(json, false);
}

export function ModuleToJSONTyped(value?: Module | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'order': value['order'],
        'module_id': value['moduleId'],
        'course_id': value['courseId'],
        'is_active': value['isActive'],
    };
}

