/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PracticeOption
 */
export interface PracticeOption {
    /**
     * 
     * @type {number}
     * @memberof PracticeOption
     */
    position: number;
    /**
     * 
     * @type {string}
     * @memberof PracticeOption
     */
    text: string;
    /**
     * 
     * @type {number}
     * @memberof PracticeOption
     */
    optionId: number;
    /**
     * 
     * @type {number}
     * @memberof PracticeOption
     */
    questionId: number;
}

/**
 * Check if a given object implements the PracticeOption interface.
 */
export function instanceOfPracticeOption(value: object): value is PracticeOption {
    if (!('position' in value) || value['position'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('optionId' in value) || value['optionId'] === undefined) return false;
    if (!('questionId' in value) || value['questionId'] === undefined) return false;
    return true;
}

export function PracticeOptionFromJSON(json: any): PracticeOption {
    return PracticeOptionFromJSONTyped(json, false);
}

export function PracticeOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PracticeOption {
    if (json == null) {
        return json;
    }
    return {
        
        'position': json['position'],
        'text': json['text'],
        'optionId': json['option_id'],
        'questionId': json['question_id'],
    };
}

export function PracticeOptionToJSON(json: any): PracticeOption {
    return PracticeOptionToJSONTyped(json, false);
}

export function PracticeOptionToJSONTyped(value?: PracticeOption | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'position': value['position'],
        'text': value['text'],
        'option_id': value['optionId'],
        'question_id': value['questionId'],
    };
}

