/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PracticeQuestion } from './PracticeQuestion';
import {
    PracticeQuestionFromJSON,
    PracticeQuestionFromJSONTyped,
    PracticeQuestionToJSON,
    PracticeQuestionToJSONTyped,
} from './PracticeQuestion';

/**
 * 
 * @export
 * @interface Practice
 */
export interface Practice {
    /**
     * 
     * @type {number}
     * @memberof Practice
     */
    position: number;
    /**
     * 
     * @type {number}
     * @memberof Practice
     */
    practiceId: number;
    /**
     * 
     * @type {number}
     * @memberof Practice
     */
    moduleId: number;
    /**
     * 
     * @type {Array<PracticeQuestion>}
     * @memberof Practice
     */
    questions?: Array<PracticeQuestion>;
}

/**
 * Check if a given object implements the Practice interface.
 */
export function instanceOfPractice(value: object): value is Practice {
    if (!('position' in value) || value['position'] === undefined) return false;
    if (!('practiceId' in value) || value['practiceId'] === undefined) return false;
    if (!('moduleId' in value) || value['moduleId'] === undefined) return false;
    return true;
}

export function PracticeFromJSON(json: any): Practice {
    return PracticeFromJSONTyped(json, false);
}

export function PracticeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Practice {
    if (json == null) {
        return json;
    }
    return {
        
        'position': json['position'],
        'practiceId': json['practice_id'],
        'moduleId': json['module_id'],
        'questions': json['questions'] == null ? undefined : ((json['questions'] as Array<any>).map(PracticeQuestionFromJSON)),
    };
}

export function PracticeToJSON(json: any): Practice {
    return PracticeToJSONTyped(json, false);
}

export function PracticeToJSONTyped(value?: Practice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'position': value['position'],
        'practice_id': value['practiceId'],
        'module_id': value['moduleId'],
        'questions': value['questions'] == null ? undefined : ((value['questions'] as Array<any>).map(PracticeQuestionToJSON)),
    };
}

