/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QuestionKeyword } from './QuestionKeyword';
import {
    QuestionKeywordFromJSON,
    QuestionKeywordFromJSONTyped,
    QuestionKeywordToJSON,
    QuestionKeywordToJSONTyped,
} from './QuestionKeyword';
import type { QuestionType } from './QuestionType';
import {
    QuestionTypeFromJSON,
    QuestionTypeFromJSONTyped,
    QuestionTypeToJSON,
    QuestionTypeToJSONTyped,
} from './QuestionType';
import type { PracticeOption } from './PracticeOption';
import {
    PracticeOptionFromJSON,
    PracticeOptionFromJSONTyped,
    PracticeOptionToJSON,
    PracticeOptionToJSONTyped,
} from './PracticeOption';

/**
 * 
 * @export
 * @interface PracticeQuestion
 */
export interface PracticeQuestion {
    /**
     * 
     * @type {number}
     * @memberof PracticeQuestion
     */
    position: number;
    /**
     * 
     * @type {QuestionType}
     * @memberof PracticeQuestion
     */
    questionType: QuestionType;
    /**
     * 
     * @type {string}
     * @memberof PracticeQuestion
     */
    question: string;
    /**
     * 
     * @type {string}
     * @memberof PracticeQuestion
     */
    correctAnswer?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PracticeQuestion
     */
    exampleAnswer?: string | null;
    /**
     * 
     * @type {Array<PracticeOption>}
     * @memberof PracticeQuestion
     */
    closedOptions?: Array<PracticeOption>;
    /**
     * 
     * @type {Array<QuestionKeyword>}
     * @memberof PracticeQuestion
     */
    openKeywords?: Array<QuestionKeyword>;
    /**
     * 
     * @type {number}
     * @memberof PracticeQuestion
     */
    questionId: number;
    /**
     * 
     * @type {number}
     * @memberof PracticeQuestion
     */
    practiceId: number;
}



/**
 * Check if a given object implements the PracticeQuestion interface.
 */
export function instanceOfPracticeQuestion(value: object): value is PracticeQuestion {
    if (!('position' in value) || value['position'] === undefined) return false;
    if (!('questionType' in value) || value['questionType'] === undefined) return false;
    if (!('question' in value) || value['question'] === undefined) return false;
    if (!('questionId' in value) || value['questionId'] === undefined) return false;
    if (!('practiceId' in value) || value['practiceId'] === undefined) return false;
    return true;
}

export function PracticeQuestionFromJSON(json: any): PracticeQuestion {
    return PracticeQuestionFromJSONTyped(json, false);
}

export function PracticeQuestionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PracticeQuestion {
    if (json == null) {
        return json;
    }
    return {
        
        'position': json['position'],
        'questionType': QuestionTypeFromJSON(json['question_type']),
        'question': json['question'],
        'correctAnswer': json['correct_answer'] == null ? undefined : json['correct_answer'],
        'exampleAnswer': json['example_answer'] == null ? undefined : json['example_answer'],
        'closedOptions': json['closed_options'] == null ? undefined : ((json['closed_options'] as Array<any>).map(PracticeOptionFromJSON)),
        'openKeywords': json['open_keywords'] == null ? undefined : ((json['open_keywords'] as Array<any>).map(QuestionKeywordFromJSON)),
        'questionId': json['question_id'],
        'practiceId': json['practice_id'],
    };
}

export function PracticeQuestionToJSON(json: any): PracticeQuestion {
    return PracticeQuestionToJSONTyped(json, false);
}

export function PracticeQuestionToJSONTyped(value?: PracticeQuestion | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'position': value['position'],
        'question_type': QuestionTypeToJSON(value['questionType']),
        'question': value['question'],
        'correct_answer': value['correctAnswer'],
        'example_answer': value['exampleAnswer'],
        'closed_options': value['closedOptions'] == null ? undefined : ((value['closedOptions'] as Array<any>).map(PracticeOptionToJSON)),
        'open_keywords': value['openKeywords'] == null ? undefined : ((value['openKeywords'] as Array<any>).map(QuestionKeywordToJSON)),
        'question_id': value['questionId'],
        'practice_id': value['practiceId'],
    };
}

