/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QuestionKeyword
 */
export interface QuestionKeyword {
    /**
     * 
     * @type {string}
     * @memberof QuestionKeyword
     */
    keyword: string;
    /**
     * 
     * @type {number}
     * @memberof QuestionKeyword
     */
    keywordId: number;
    /**
     * 
     * @type {number}
     * @memberof QuestionKeyword
     */
    questionId: number;
}

/**
 * Check if a given object implements the QuestionKeyword interface.
 */
export function instanceOfQuestionKeyword(value: object): value is QuestionKeyword {
    if (!('keyword' in value) || value['keyword'] === undefined) return false;
    if (!('keywordId' in value) || value['keywordId'] === undefined) return false;
    if (!('questionId' in value) || value['questionId'] === undefined) return false;
    return true;
}

export function QuestionKeywordFromJSON(json: any): QuestionKeyword {
    return QuestionKeywordFromJSONTyped(json, false);
}

export function QuestionKeywordFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuestionKeyword {
    if (json == null) {
        return json;
    }
    return {
        
        'keyword': json['keyword'],
        'keywordId': json['keyword_id'],
        'questionId': json['question_id'],
    };
}

export function QuestionKeywordToJSON(json: any): QuestionKeyword {
    return QuestionKeywordToJSONTyped(json, false);
}

export function QuestionKeywordToJSONTyped(value?: QuestionKeyword | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'keyword': value['keyword'],
        'keyword_id': value['keywordId'],
        'question_id': value['questionId'],
    };
}

