name: Lint Check

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4        
      - uses: astral-sh/ruff-action@v3   

      - name: Run ruff
        working-directory: backend/api  
        run: ruff check .